# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 630)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 601, 631))
        self.frame.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(370, 600, 161, 20))
        self.label_3.setStyleSheet("color: rgb(250, 250, 250);\n"
"background-color: rgb(19, 19, 19);")
        self.label_3.setObjectName("label_3")
        self.LOGIN = QtWidgets.QLineEdit(self.frame)
        self.LOGIN.setGeometry(QtCore.QRect(220, 520, 91, 31))
        self.LOGIN.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.LOGIN.setObjectName("LOGIN")
        self.Password = QtWidgets.QLineEdit(self.frame)
        self.Password.setGeometry(QtCore.QRect(32, 300, 481, 61))
        self.Password.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.Password.setObjectName("Password")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(240, 270, 41, 21))
        self.label_2.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(249, 249, 249);")
        self.label_2.setObjectName("label_2")
        self.Password_2 = QtWidgets.QLineEdit(self.frame)
        self.Password_2.setGeometry(QtCore.QRect(30, 180, 481, 61))
        self.Password_2.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.Password_2.setObjectName("Password_2")
        self.Password_3 = QtWidgets.QLineEdit(self.frame)
        self.Password_3.setGeometry(QtCore.QRect(30, 420, 481, 61))
        self.Password_3.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.Password_3.setObjectName("Password_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(200, 150, 121, 21))
        self.label.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(249, 249, 249);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(220, 390, 81, 21))
        self.label_4.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(249, 249, 249);")
        self.label_4.setObjectName("label_4")
        self.Selamatdatangdiwevsitependaftaranakunbelajar = QtWidgets.QLineEdit(self.frame)
        self.Selamatdatangdiwevsitependaftaranakunbelajar.setGeometry(QtCore.QRect(20, 30, 491, 31))
        self.Selamatdatangdiwevsitependaftaranakunbelajar.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.Selamatdatangdiwevsitependaftaranakunbelajar.setDragEnabled(True)
        self.Selamatdatangdiwevsitependaftaranakunbelajar.setReadOnly(True)
        self.Selamatdatangdiwevsitependaftaranakunbelajar.setObjectName("Selamatdatangdiwevsitependaftaranakunbelajar")
        self.Register = QtWidgets.QLineEdit(self.frame)
        self.Register.setGeometry(QtCore.QRect(210, 80, 101, 31))
        self.Register.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Register.setObjectName("Register")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "   creat by Kaleb G Palapa"))
        self.LOGIN.setText(_translate("Dialog", "                 LOGIN"))
        self.label_2.setText(_translate("Dialog", "Email"))
        self.label.setText(_translate("Dialog", "Nama Lengkap"))
        self.label_4.setText(_translate("Dialog", " Password"))
        self.Selamatdatangdiwevsitependaftaranakunbelajar.setText(_translate("Dialog", "Selamat datang di website pendaftaran akun belajar"))
        self.Register.setText(_translate("Dialog", "       Register "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
